#
# Test file for testing casing validation of GitHub actions
#

name: Valid action
description: |
  This action is used for testing and should be VALID with respect to
  casing of inputs and outputs fields.

inputs:
  first_input:
    description: First input
    required: true
  second_input:
    description: Second input
    required: false
    default: ""
outputs:
  first_output:
    description: First output
    value: ${{ steps.determine_output.outputs.my_output }}

runs:
  using: composite
  steps:
    - name: First step
      id: determine_output
      shell: bash
      run: |
        # Write inputs
        echo ${{ inputs.first_input }}
        echo ${{ inputs.second_input }}
        # Set outputs
        echo "my_output='output-data'" >>$GITHUB_OUTPUT

    - name: Zip folder
      uses: thedoctor0/zip-release@master
      with:
        type: zip
        filename: my_file.zip
        directory: my_folder
