name: Azure OIDC login
description: Azure login action

inputs:
  client_id:
    description: "Azure client ID"
    required: true
  tenant_id:
    description: "Azure tenant ID"
    required: true
  subscription_id:
    description: "Azure subscription ID"
    required: true

runs:
  using: composite
  steps:
    - name: Is logged in
      id: isloggedin
      shell: pwsh
      run: |
        if ($null -eq (az account show)) {
          echo "isloggedin=false" >> $env:GITHUB_OUTPUT
        } else {
          echo "isloggedin=true" >> $env:GITHUB_OUTPUT
        }

    - name: Az CLI login
      if: ${{ steps.isloggedin.outputs.isloggedin == 'false' }}
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}

    # - name: Log in to Azure using OIDC
    #   shell: pwsh
    #   run: |
    #     #$clientId = '${{ inputs.client_id }}'
    #     #$tenantId = '${{ inputs.tenant_id }}'
    #     #$subscriptionId = '${{ inputs.subscription_id }}'

    #     $clientId = 'e3b3ad4b-772b-4141-aa1d-1701321edbad'
    #     $tenantId = 'f7619355-6c67-4100-9a78-1847f30742e2'
    #     $subscriptionId = '95146aa1-8115-4c82-8506-1f943227ceba'

    #     ${{ github.action_path }}/New-AzureLogin.ps1 -ClientId $clientId -TenantId $tenantId -SubscriptionId $subscriptionId
