name: Azure OIDC login
description: Azure login action

inputs:
  azure_client_id:
    description: "Azure client ID"
    required: true
  azure_tenant_id:
    description: "Azure tenant ID"
    required: true
  azure_subscription_id:
    description: "Azure subscription ID"
    required: true

runs:
  using: composite
  steps:
    - name: Create release tag
      shell: pwsh
      env:
        AZURE_CLIENT_ID: ${{ inputs.azure_client_id }}
        AZURE_TENANT_ID: ${{ inputs.azure_tenant_id }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
      run: |
        ${{ github.action_path }}/New-AzureLogin.ps1.ps1
