name: Azure OIDC login
description: Azure login action

inputs:
  client_id:
    description: "Azure client ID"
    required: true
  tenant_id:
    description: "Azure tenant ID"
    required: true
  subscription_id:
    description: "Azure subscription ID"
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Azure using OIDC
      shell: pwsh
      env:
        AZURE_CLIENT_ID: ${{ inputs.client_id }}
        AZURE_TENANT_ID: ${{ inputs.tenant_id }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
      run: |
        ${{ github.action_path }}/New-AzureLogin.ps1
