name: Azure OIDC login
description: Azure login action

inputs:
  client_id:
    description: "Azure client ID"
    required: true
  tenant_id:
    description: "Azure tenant ID"
    required: true
  subscription_id:
    description: "Azure subscription ID"
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Azure using OIDC
      shell: pwsh
      run: |
        ${{ github.action_path }}/New-AzureLogin.ps1 -applicationId ${{ inputs.client_id }} -tenantId ${{ inputs.tenant_id }} -subscription ${{ inputs.subscription_id }}
