name: Azure OIDC login
description: Azure login action

inputs:
  client_id:
    description: "Azure client ID"
    required: true
  tenant_id:
    description: "Azure tenant ID"
    required: true
  subscription_id:
    description: "Azure subscription ID"
    required: true

runs:
  using: composite
  steps:
    - name: Is logged in
      continue-on-error: true
      id: isloggedin
      shell: pwsh
      run: |
        try {
          if ($null -eq (az account get-access-token --resource-type ms-graph 2>nul)) {
            echo "isloggedin=false" >> $env:GITHUB_OUTPUT
            exit 0
          } else {
            Write-Host 'Token already exists'
            echo "isloggedin=true" >> $env:GITHUB_OUTPUT
          }
        }
        catch {
          Write-Host 'We have exploded'
          Write-Host $_.Message
          Write-Host $_.Exception
        }

    - name: Az CLI login
      if: ${{ steps.isloggedin.outputs.isloggedin == 'false' }}
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}

    # - name: Sleep for 11 minutes to test behaviour when id token has expired
    #   shell: pwsh
    #   run: |
    #     Start-Sleep -Seconds 660
