name: Python Test
description: Test a package with pytest
inputs:
  name:
    description: The name of the package
    required: true
  pat_token:
    description: The GitHub PAT token for authentication
    required: true
  path:
    description: The path to the package
    required: true
  tests_path:
    description: The path to the tests
    required: false
    default: tests
  pytest_addopts:
    description: Additional arguments to pass to pytest
    required: false
    default: ""
  publish_test_report:
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      with:
        enable-cache: true
        ignore-nothing-to-cache: true
        cache-suffix: ${{ inputs.name }}
        cache-dependency-glob: |
          ${{ inputs.path }}/pyproject.toml
          ${{ inputs.path }}/uv.lock

    - name: Inject pat_token into git configuration
      shell: bash
      run: |
        git config --global url."https://oauth2:${{ inputs.pat_token }}@github.com".insteadOf https://github.com

    - name: Test
      shell: bash
      run: uv run --directory ${{ inputs.path }} pytest ${{ inputs.tests_path }} ${{ inputs.pytest_addopts }} --junit-xml=coverage.xml

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action/linux@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
      if: ${{ always() && inputs.publish_test_report == 'true' }}
      with:
        check_name: Python test results for '${{ inputs.path }}' with ${{ inputs.pytest_addopts }}
        comment_title: Python test results for '${{ inputs.name }}' with ${{ inputs.pytest_addopts }}
        comment_mode: failures
        files: |
          ${{ inputs.path }}/coverage.xml
