name: Build dotnet solution
description: Setup .NET and other tools typically used when building and testing .NET code

inputs:
  solution_directory:
    description: The path to the solution directory
    required: true

  solution_filename:
    description: The name of the solution file (e.g. MySolution.sln)
    required: true

  configuration:
    description: The build configuration to use (e.g. Release, Debug)
    required: false
    default: Release

  pull_request_number:
    description: The pull request number to use for the build metadata
    required: true

  sha:
    description: The SHA to use for the build metadata
    required: true

steps:

  - name: Cache NuGet packages
    uses: actions/cache@v4
    id: cache-nuget
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} # hash of project files
      restore-keys: |
        ${{ runner.os }}-nuget-

  - name: Restore NuGet packages
    run: dotnet restore ${{ inputs.solution_directory }}/${{ inputs.solution_filename }}


    # We build the GitHub PR and SHA (last merge commit on PR) into the .NET assembly meta data:
    #   The full 'InformationalVersion' format is '<version>+PR_<pr number>+SHA_<sha>'.
    #
    #   The value of 'SourceRevisionId' is appended to the assembly attribute 'InformationalVersion', separated by a '+' sign.
    #   See: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generateassemblyinfo
    #
  - name: Build solution
    run: |
      dotnet build ${{ inputs.solution_directory }}/${{ inputs.solution_filename }} --no-restore --configuration ${{ inputs.configuration }} -p:SourceRevisionId=PR_${{ inputs.pull_request_number }}+SHA_${{ inputs.sha }}
