# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: 'Common steps for dotnet projects'
description: 'Builds and tests dotnet projects.'
inputs:
  RELEASE_FOLDER_PATH:
    required: true
  RELEASE_VERSION:
    required: true
  PAT_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Zip artifact
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: ${{ inputs.RELEASE_VERSION }}.zip
        directory: ${{ inputs.RELEASE_FOLDER_PATH }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ inputs.PAT_TOKEN }}"
        automatic_release_tag: ${{ inputs.RELEASE_VERSION }}
        prerelease: true
        title: ${{ inputs.RELEASE_VERSION }}
        files: |
          ${{ inputs.RELEASE_FOLDER_PATH }}/${{ inputs.RELEASE_VERSION }}.zip