name: Build and push docker containers to ghcr.io
description: |
  This action will ensure the image name is lowercased and that any artifacts are available.

inputs:
  dockerfile:
    description: The path of the Dockerfile to build
    required: true
  image-name:
    description: The full image name excluding ghcr.io/<my_container>
    required: true
  image-tag:
    description: The image tag
    required: true
  docker-context:
    description: The path for the docker build context, defaults to '.'
    required: false
    default: .
  dry-run:
    description: Perform all actions but without committing changes
    required: false
    default: "false"
  build-args:
    description: List of build-time variables
    required: false

outputs:
  image:
    description: Full image reference with tag
    value: ${{ steps.tag.outputs.image }}
  digest:
    description: Pushed image digest
    value: ${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      name: Download available artifacts # this supports use of artifacts (currently only frontends)
      with:
        path: artifacts/

    - name: Resolve container image name
      id: tag
      shell: bash
      run: echo "LOWERCASED=$(echo 'ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV && echo "image=$(echo 'ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}' | tr '[:upper:]' '[:lower:]'):${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

    - name: Log in to the Container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        ecr: false

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.dry-run != 'true' }}
        pull: true
        tags: ${{ env.LOWERCASED }}:${{ inputs.image-tag }}
        build-args: ${{ inputs.build-args }}
