#
# Test file for testing casing validation of GitHub workflows
#

name: Valid workflow
description: |
  This workflow is used for testing and should be VALID with respect to
  casing of inputs, outputs and secrets fields.

on:
  workflow_call:
    inputs:
      first_input:
        description: First input
        required: true
      second_input:
        description: Second input
        required: false
        default: ""
    outputs:
      first_output:
        description: First output
        value: ${{ jobs.changes.outputs.magic }}
    secrets:
      first_secret:
        required: true
        description: First secret
  workflow_dispatch:
    inputs:
      first_dispatch:
        description: First dispatch input
        required: false

jobs:
  changes:
    name: Determine magic
    runs-on: ubuntu-latest
    outputs:
      magic: ${{ steps.filter.outputs.magic }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect file changes
        uses: ./.github/paths-filter@v2
        id: filter
        with:
          filters: |
            magic:
              - '.github/workflows/magic-*.yml'

  ci_magic_build:
    needs: changes
    if: ${{ needs.changes.outputs.magic == 'true' }}
    uses: ./.github/workflows/ci-magic-build.yml
    with:
      solution_file_path: my.sln
    secrets: inherit

  ci_magic_test:
    needs: ci_magic_build
    uses: Energinet-DataHub/.github/.github/workflows/ci-magic-test.yml@v13
    with:
      solution_file_path: my.sln
    secrets:
      secret_url: my_secret_url
