# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Build, tests and publishes a .NET project'
description: 'Build, tests and publishes a .NET project'
inputs:
  PROJECT_NAME:
    required: true
  ORGANISATION_NAME:
    required: true
  ENVIRONMENT_SHORT:
    required: true
  ENVIRONMENT_NAME:
    required: true
  TERRAFORM_BACKEND_FILE_PATH:
    required: true
  TERRAFORM_WORKING_DIR_PATH:
    required: true
  AZURE_TENANT_ID:
    required: true
  AZURE_SPN_ID:
    required: true
  AZURE_SPN_OBJECT_ID:
    required: true
  AZURE_SPN_SECRET:
    required: true
  AZURE_SUBSCRIPTION_ID:
    required: true
  AZURE_RG_NAME:
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment Secrets
      shell: bash
      run: |  
        echo "TERRAFORM_STORAGE_NAME=tfstate${{ inputs.PROJECT_NAME }}${{ inputs.ENVIRONMENT_SHORT }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ inputs.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ inputs.AZURE_SPN_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_OBJECT_ID=${{ inputs.AZURE_SPN_OBJECT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ inputs.AZURE_SPN_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    - name: Azure CLI Install
      shell: bash
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure CLI Login
      shell: bash
      run: |
        az login --service-principal --username "${{ inputs.AZURE_SPN_ID }}" --password "${{ inputs.AZURE_SPN_SECRET }}" --tenant "${{ inputs.AZURE_TENANT_ID }}"
        az account set --subscription "${{ inputs.AZURE_SUBSCRIPTION_ID }}"

    - name: Setup Authorization to pull TF modules
      shell: bash
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://foo:bar@github.com/Energinet-DataHub/geh-terraform-modules".insteadOf "https://github.com/Energinet-DataHub/geh-terraform-modules"
    
    - name: Find or create Terraform storage
      shell: bash
      id: state-storage-exists
      run: |
        storage_exists=$(az storage account check-name --name ${{ env.TERRAFORM_STORAGE_NAME }} | python3 -c "import sys, json; print(not json.load(sys.stdin)['nameAvailable'])")
        if [ "$storage_exists" = True ]; then
          echo "Storage exists";
          exit;
        fi
        az storage account create --resource-group ${{ inputs.AZURE_RG_NAME }} --name ${{ env.TERRAFORM_STORAGE_NAME }} --sku Standard_LRS --encryption-services blob --min-tls-version TLS1_2
        account_key=$(az storage account keys list --resource-group ${{ inputs.AZURE_RG_NAME }} --account-name ${{ env.TERRAFORM_STORAGE_NAME }} --query '[0].value' -o tsv)
        az storage container create --name tfstate --account-name ${{ env.TERRAFORM_STORAGE_NAME }} --account-key $account_key

    # Try not to reference TF_VAR variables in pipeline yml files, only values should be set and they should be read in terraform only
    # rather create duplicate ENV pipeline vatiable if needed to separate concerns
    - name: Set TF Vars
      shell: bash
      run: |
        echo "TF_VAR_environment=${{ inputs.ENVIRONMENT_SHORT }}" >> $GITHUB_ENV
        echo "TF_VAR_organisation=${{ inputs.ORGANISATION_NAME }}" >> $GITHUB_ENV
        echo "TF_VAR_project=${{ inputs.PROJECT_NAME }}" >> $GITHUB_ENV
        echo "TF_VAR_resource_group_name=${{ inputs.AZURE_RG_NAME }}" >> $GITHUB_ENV
    
    # Override/overwrite with environment specific infrastructure
    - name: Configure environment specific infrastructure
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_WORKING_DIR_PATH }}
      run: |
        cp -fR ../env/${{ inputs.ENVIRONMENT_NAME }}/* ./ 2>/dev/null || :
    
    - name: Configure Terraform Backend
      shell: bash
      run: |
        sed -i 's/@resource_group_name/${{ inputs.AZURE_RG_NAME }}/' ${{ inputs.TERRAFORM_BACKEND_FILE_PATH }}
        sed -i 's/@storage_account_name/${{ env.TERRAFORM_STORAGE_NAME }}/' ${{ inputs.TERRAFORM_BACKEND_FILE_PATH }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_WORKING_DIR_PATH }}
      run: terraform init

    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.TERRAFORM_WORKING_DIR_PATH }}
      run: terraform plan

    - name: Terraform Apply
      shell: bash
      id: terraform-apply
      working-directory: ${{ inputs.TERRAFORM_WORKING_DIR_PATH }}
      run: terraform apply -no-color -auto-approve
