#
# Test file for testing casing validation of GitHub workflows
#

name: Invalid workflow
description: |
  This workflow is used for testing and should be INVALID with respect to
  casing of inputs, outputs and secrets fields.

on:
  workflow_call:
    inputs:
      first_INPUT:
        description: First input
        required: true
      SECOND_input:
        description: Second input
        required: false
        default: ""
    outputs:
      first_OUTPUT:
        description: First output
        value: ${{ jobs.changes.outputs.magic }}
    secrets:
      FIRST_secret:
        required: true
        description: First secret
  workflow_dispatch:
    inputs:
      FIRST_DISPATCH:
        description: First dispatch input
        required: false

jobs:
  changes:
    name: Determine magic
    runs-on: ubuntu-latest
    outputs:
      MAgic: ${{ steps.filter.outputs.magic }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          FILTERS: |
            magic:
              - '.github/workflows/magic-*.yml'

  ci_magic_build:
    needs: changes
    if: ${{ needs.changes.outputs.magic == 'true' }}
    uses: ./.github/workflows/ci-magic-build.yml
    with:
      SOLUTION_file_path: my.sln
    secrets: INHERIT

  ci_magic_test:
    needs: ci_magic_build
    uses: Energinet-DataHub/.github/.github/workflows/ci-magic-test.yml@v12
    with:
      solution_FILE_path: my.sln
    secrets:
      secret_URL: my_secret_url
