name: Automatic Releases
description: Automate the GitHub release process with assets, changelogs, pre-releases, and more
branding:
  icon: package
  color: blue
inputs:
  repo_token:
    description: GitHub secret token
    required: true
  automatic_release_tag:
    description: Git tag (for automatic releases)
    required: false
  prerelease:
    description: Should this release be marked as a pre-release?
    required: false
    default: true
  title:
    description: Release title (for automatic releases)
    required: false
  files:
    description: Assets to upload to the release
    required: false
outputs:
  automatic_releases_tag:
    description: The release tag this action just processed
  upload_url:
    description: The URL for uploading additional assets to the release
  pull_request_number:
    description: The pull request number associated with the release
    value: ${{ steps.create_release.outputs.pull_request_number }}
  sha:
    description: The commit SHA associated with the release
    value: ${{ steps.create_release.outputs.sha }}
runs:
  using: composite
  steps:
    - name: Create automatic release
      id: create_release
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.repo_token }}
        GH_CONTEXT: ${{ toJSON(github) }}
      run: |
        . ${{ github.action_path }}/Create-GitHubRelease.ps1

        Create-GitHubRelease `
          -TagName "${{ inputs.automatic_release_tag }}" `
          -PreRelease "${{ inputs.prerelease }}" `
          -title "${{ inputs.title }}" `
          -files "${{ inputs.files }}"
