name: Zip and Unzip
description: GitHub Action to zip and unzip files and directories.
inputs:
  action:
    description: 'zip or unzip'
    required: true
  source:
    description: 'Source file or directory (for zip) or archive (for unzip)'
    required: true
  destination:
    description: 'Destination zip file (for zip) or directory (for unzip)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Zip files
      if: ${{ inputs.action == 'zip' }}
      shell: bash
      env:
        CONTENT_PATH: ${{ inputs.source }}
        ARCHIVE_FILENAME: ${{ inputs.destination }}
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          7z a -tzip -bso0 -bsp0 "$ARCHIVE_FILENAME" "$CONTENT_PATH"
        else
          zip -q -r "$ARCHIVE_FILENAME" "$CONTENT_PATH"
        fi

        echo "Created zip archive at $ARCHIVE_FILENAME from $CONTENT_PATH"

    - name: Unzip files
      if: ${{ inputs.action == 'unzip' }}
      shell: bash
      env:
        ARCHIVE_FILENAME: ${{ inputs.source }}
        DESTINATION_PATH: ${{ inputs.destination }}
      run: |
        mkdir -p "$DESTINATION_PATH"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          7z x -bso0 -bsp0 "$ARCHIVE_FILENAME" -o"$DESTINATION_PATH" -y
        else
          unzip -q "$ARCHIVE_FILENAME" -d "$DESTINATION_PATH"
        fi

        echo "Extracted zip archive to $DESTINATION_PATH from $ARCHIVE_FILENAME"
