name: PySpark execution
description: This action allows you to execute code, written for Spark, Databricks or other similar engines.

inputs:
  image_tag:
    description: The tag of the docker image to use
    required: true
  tests_filter_expression:
    description: Filter expression to use with pytest. Read description in 'entrypoint.sh'.
    required: true

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Execute python tests
      shell: bash
      run: |
        # Small hack to get the repository name
        repository=${{ github.repository }}
        repository_owner=${{ github.repository_owner }}
        repository_name=${repository/$repository_owner\//}

        chmod +x ./.docker/entrypoint.sh
        IMAGE_TAG=${{ inputs.image_tag }} docker-compose -f .devcontainer/docker-compose.yml run --rm -u root -w //workspaces/${repository_name} python-unit-test ./.docker/entrypoint.sh "${{ inputs.tests_filter_expression }}"
