name: PySpark execution
description: This action allows you to execute code, written for Spark, Databricks or other similar engines.

inputs:
  image_tag:
    description: The tag of the docker image to use
    required: true
  tests_folder_path:
    description: The path to the (root) folder containing the tests
    required: false
  tests_filter_expression:
    description: |
      Filter expression to use with pytest. Read description in 'entrypoint.sh'.
      Filter expressions are relative to the tests_folder_path.
    required: true

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Execute python tests
      shell: bash
      run: |
        if [ -n "${{ inputs.tests_folder_path }}" ]; then
          IMAGE_TAG=${{ inputs.image_tag }} docker compose -f .devcontainer/docker-compose.yml run --rm python-unit-test ./.docker/entrypoint.sh "${{ inputs.tests_folder_path }}" "${{ inputs.tests_filter_expression }}"
        else
          IMAGE_TAG=${{ inputs.image_tag }} docker compose -f .devcontainer/docker-compose.yml run --rm python-unit-test ./.docker/entrypoint.sh "${{ inputs.tests_filter_expression }}"
        fi
