name: CI orchestrator

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: ./workflows/ci-base.yml
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey}}

  #
  # Automatic Release (verify if release tag exists)
  #
  create_release:
    uses: ./workflows/create-release-tag.yml
    secrets: inherit

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, create_release]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
