name: Create release tag

on:
  workflow_call: {}

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Energinet-DataHub/.github/actions/github-create-token@v14
        name: Generate Github token
        id: generate_token
        with:
          app_id: ${{ vars.dh3serviceaccount_appid }}
          private_key: ${{ secrets.dh3serviceaccount_privatekey }}

      - name: Create release
        uses: ./.github/actions/create-release-tag
        with:
          # BE AWARE --> Updating to a new MAJOR version will delete deprecated versions on a nightly schedule.
          # See https://github.com/Energinet-DataHub/.github#release-procedure for details
          major_version: 15
          minor_version: 0
          patch_version: 0
          repository_path: Energinet-DataHub/.github
          usage_patterns: \s*uses:\s*Energinet-DataHub/\.github(.*)@v?(?<version>\d+)
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
