# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and test dotnet solution
description: Build a .NET solution, run tests and upload code coverage

inputs:
  solution_file_path:
    required: true
  build_configuration:
    required: false
    default: Release
  # Secrets required if we need to login to Azure and use Azure resources from automated tests
  azure_tenant_id:
    required: false
  azure_subscription_id:
    required: false
  azure_spn_id:
    required: false
  publish_test_report:
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Guard for Windows OS
      shell: bash
      run: |
        echo "Runner OS is $RUNNER_OS"
        if [ $RUNNER_OS == 'Windows' ]; then
          echo "$RUNNER_OS is supported"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi

    # Downgrade Azure CLI to v2.58.0 to workaround bug in v2.59.0
    # When v2.60.0 is released we can remove this again.
    # See https://github.com/Azure/login/issues/372#issuecomment-2056289617
    - name: uninstall azure-cli
      shell: pwsh
      run: |
        Start-Process msiexec.exe -Wait -ArgumentList '/x {DEFB65A7-FD02-4710-B01E-6C9387982CA9} /quiet'
    - name: install azure-cli 2.58.0
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://azcliprod.blob.core.windows.net/msi/azure-cli-2.58.0-x64.msi -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item .\AzureCLI.msi
    - name: check azure-cli version
      shell: pwsh
      run: |
        az --version
    - uses: azure/cli@v2
      with:
        azcliversion: 2.58.0
        inlineScript: |
          # Storage:
          az account get-access-token --scope https://storage.azure.com/.default --output none
          # Key Vault:
          az account get-access-token --scope https://vault.azure.net/.default --output none
          # Microsoft Graph:
          az account get-access-token --scope https://graph.microsoft.com/.default --output none
          # Kusto:
          az account get-access-token --scope https://kusto.kusto.windows.net/.default --output none

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore ${{ inputs.solution_file_path }}

    - name: Build solution
      shell: pwsh
      run: |
        dotnet build ${{ inputs.solution_file_path }} --no-restore --configuration ${{ inputs.build_configuration }}

    - name: Login to use Azure resources from automated tests
      if: ${{ inputs.azure_tenant_id != '' }}
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_spn_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Run tests
      shell: pwsh
      id: run_tests
      run: |
        dotnet tool install --tool-path ./temp/reportgenerator dotnet-reportgenerator-globaltool
        dotnet test ${{ inputs.solution_file_path }} --no-build --configuration ${{ inputs.build_configuration }} --verbosity normal --logger "trx;logfilename=testResults.trx" --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover --output ${{ github.workspace }}\output

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: inputs.publish_test_report == 'true' || (failure() && steps.run_tests.conclusion == 'failure' && inputs.publish_test_report == 'true') # Reference_ https://docs.github.com/en/actions/learn-github-actions/expressions#failure-with-conditions
      with:
        check_name: Test results for ${{ inputs.solution_file_path }}
        comment_title: Test results for ${{ inputs.solution_file_path }}
        comment_mode: failures
        files: |
          **/TestResults/*.trx
