name: Install tools
description: Use asdf to install tools specified in .tool-versions
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

    - name: Check for existence of .tool-versions file
      id: check_tool_versions
      shell: bash
      run: |
        if [ ! -f .tool-versions ]; then
          echo "exists=false" >>$GITHUB_OUTPUT
        else
          echo "exists=true" >>$GITHUB_OUTPUT
        fi

    - name: Setup asdf
      uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      if: ${{ steps.check_tool_versions.outputs.exists == 'true' }}

    - name: Restore asdf cache
      uses: actions/cache/restore@caa296126883cff596d87d8935842f9db880ef25 # v5
      if: ${{ steps.check_tool_versions.outputs.exists == 'true' }}
      id: cache-asdf-restore
      with:
        path: /home/runner/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}

    - name: Install dependencies in .tool-versions
      uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      if: ${{ steps.check_tool_versions.outputs.exists == 'true' }}

    - name: Save asdf cache
      uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5
      if: ${{ steps.cache-asdf-restore.outputs.cache-hit != 'true' && steps.check_tool_versions.outputs.exists == 'true' }}
      with:
        path: /home/runner/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
