name: "Python Covernator Commit"
description: "Generate and commit Covernator coverage results"

inputs:
  project_directory:
    required: true
    description: "Path to the project root (where tests/ live)"
  geh_common_version:
    required: false
    default: "7.2.2"
    description: "geh_common package version"

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1️⃣ Checkout domain repo
    # -------------------------------------------------------------------------
    - name: Checkout domain repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # -------------------------------------------------------------------------
    # 2️⃣ Setup Python + UV
    # -------------------------------------------------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    # -------------------------------------------------------------------------
    # 3️⃣ Install geh_common from branch or tag
    # -------------------------------------------------------------------------
    - name: Install geh_common
      shell: bash
      run: |
        echo "Installing geh_common from branch ${{ inputs.geh_common_version }}"
        uv pip install --system \
          "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@${{ inputs.geh_common_version }}#subdirectory=source/geh_common"

    # -------------------------------------------------------------------------
    # 4️⃣ Run covernator analysis + markdown generation
    # -------------------------------------------------------------------------
    - name: Run Covernator + Markdown generator
      shell: bash
      run: |
        python - <<'PYCODE'
        import os
        from geh_common.testing.covernator.entrypoints import run_and_generate_markdown

        project_dir = os.getenv("PROJECT_DIRECTORY")
        if not project_dir:
            raise ValueError("Missing PROJECT_DIRECTORY input for Covernator action.")

        print(f"🔍 Running Covernator analysis on: {project_dir}")
        run_and_generate_markdown(project_dir)
        PYCODE
      env:
        PROJECT_DIRECTORY: ${{ inputs.project_directory }}

    # -------------------------------------------------------------------------
    # 5️⃣ Commit the results (only on main)
    # -------------------------------------------------------------------------
    - name: Commit and push markdown to docs (main only)
      if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🧩 Update Covernator results [skip ci]"
        file_pattern: docs/covernator/coverage_overview.md
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
