name: "Python Covernator Commit"
description: "Generate and display Covernator coverage results (Step 1: stats in PR comment)"

inputs:
  project_directory:
    required: true
    description: "Path to the project root (where tests/ live)"
  geh_common_version:
    required: false
    default: "7.2.1"
    description: "geh_common package version"

runs:
  using: "composite"
  steps:
    - name: Checkout domain repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install geh_common
      shell: bash
      run: |
        echo "Installing geh_common version ${{ inputs.geh_common_version }}"
        uv pip install --system \
          "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@geh_common_${{ inputs.geh_common_version }}#subdirectory=source/geh_common"

    - name: Run Covernator locally
      id: covernator
      shell: bash
      run: |
        mkdir -p docs/covernator
        echo "▶ Running Covernator on ${{ inputs.project_directory }}"
        python -m geh_common.covernator_streamlit.server \
          -g \
          -o docs/covernator \
          -k stats \
          -p ${{ inputs.project_directory }}

        echo "▶ Generated files in docs/covernator:"
        ls -lah docs/covernator

        echo "▶ Preview of stats.json:"
        head -n 20 docs/covernator/stats.json || echo "No stats.json found"

        # Encode JSON safely
        encoded=$(base64 -w 0 docs/covernator/stats.json)
        echo "stats_json_b64=$encoded" >> "$GITHUB_OUTPUT"

    # Decode JSON and store to output file (safe for mshick/add-pr-comment)
    - name: Decode stats JSON (safe compact)
      id: decode
      shell: bash
      run: |
        mkdir -p temp
        echo "${{ steps.covernator.outputs.stats_json_b64 }}" | base64 --decode > temp/stats.json
        echo "Decoded JSON (raw):"
        cat temp/stats.json
        echo

        # Compact to single-line JSON using jq
        safe_json=$(jq -c . temp/stats.json)
        echo "Compact JSON for output:"
        echo "$safe_json"

        # Write safely to GITHUB_OUTPUT
        echo "stats_json=$safe_json" >> "$GITHUB_OUTPUT"


    - name: Add PR comment with stats
      uses: mshick/add-pr-comment@v2
      with:
        message-id: covernator-stats
        message: |
          🧩 **Python Covernator Commit**
          ✅ Successfully generated Covernator results for `${{ github.repository }}`

          **Stats summary**
          ```json
          ${{ steps.decode.outputs.stats_json }}
          ```

          **geh_common version:** ${{ inputs.geh_common_version }}
          **Branch:** `${{ github.ref_name }}`
          **Generated:** $(TZ="Europe/Copenhagen" date '+%Y-%m-%d %H:%M:%S %Z')
