name: "Covernator test action"
description: "Simple test action to verify branch-based execution from .github repo"

inputs:
  project_directory:
    required: false
    default: "."
    description: "Dummy input (kept for compatibility)"
  geh_common_version:
    required: false
    default: "7.2.1"
    description: "Dummy input (kept for compatibility)"

runs:
  using: "composite"
  steps:
    - name: Print CET time and context
      id: print
      shell: bash
      run: |
        echo "I am on a test branch of .github"
        CET_TIME=$(TZ="Europe/Copenhagen" date '+%Y-%m-%d %H:%M:%S %Z')
        echo "The time is $CET_TIME"
        echo "time_message=The time is $CET_TIME" >> $GITHUB_OUTPUT

    - name: Add PR comment (test branch)
      uses: mshick/add-pr-comment@v2
      with:
        message-id: covernator-test
        message: |
          🧪 **Covernator test branch action**
          - I am on a test branch of `.github`
          - The time is **${{ steps.print.outputs.time_message }}**
