name: "Python Covernator Generate Files"
description: "Runs Covernator coverage analysis, generates Markdown, and commits results (main branch only)."

inputs:
  project_directory:
    description: "Path to the project source folder."
    required: true

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1️⃣ Setup Python environment
    # -------------------------------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # -------------------------------------------------------------------------
    # 2️⃣ Install dependencies
    # -------------------------------------------------------------------------
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install geh-common
        echo "✅ geh-common package installed."

    # -------------------------------------------------------------------------
    # 3️⃣ Verify working directory and environment
    # -------------------------------------------------------------------------
    - name: Verify environment
      shell: bash
      run: |
        echo "📂 Current directory: $(pwd)"
        echo "📦 Python version: $(python --version)"
        echo "🌿 GitHub ref: $GITHUB_REF"
        echo "🧪 Event name: $GITHUB_EVENT_NAME"

    # -------------------------------------------------------------------------
    # 4️⃣ Run Covernator analysis + markdown generation (only on main)
    # -------------------------------------------------------------------------
    - name: Run Covernator + Markdown generator
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        python - <<'PYCODE'
        import os
        from geh_common.testing.covernator.entrypoints import run_and_generate_markdown

        project_dir = os.getenv("PROJECT_DIRECTORY")
        if not project_dir:
            raise ValueError("Missing PROJECT_DIRECTORY input for Covernator action.")

        print(f"🔍 Running Covernator analysis on: {project_dir}")
        run_and_generate_markdown(project_dir)
        PYCODE
      env:
        PROJECT_DIRECTORY: ${{ inputs.project_directory }}

    # -------------------------------------------------------------------------
    # 5️⃣ Commit the results (only on main)
    # -------------------------------------------------------------------------
    - name: Commit and push markdown to docs (main only)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🧩 Update Covernator results [skip ci]"
        file_pattern: docs/covernator/coverage_overview.md
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com

    # -------------------------------------------------------------------------
    # 6️⃣ Log skipped execution on non-main branches
    # -------------------------------------------------------------------------
    - name: Skip Covernator on non-main branches
      if: github.event_name != 'push' || github.ref != 'refs/heads/main'
      shell: bash
      run: echo "🧱 Skipping Covernator — this action only runs on push to main."
