name: "Python Covernator Commit"
description: "Generate and display Covernator coverage results (Step 1: PR comment only)"

inputs:
  project_directory:
    required: true
    description: "Path to the project root (where tests/ live)"
  geh_common_version:
    required: false
    default: "7.2.1"
    description: "geh_common package version"

runs:
  using: "composite"
  steps:
    - name: Checkout domain repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Install geh_common
      shell: bash
      run: |
        echo "Installing geh_common version ${{ inputs.geh_common_version }}"
        uv pip install --system \
          "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@geh_common_${{ inputs.geh_common_version }}#subdirectory=source/geh_common"

    - name: Run Covernator locally
      id: covernator
      shell: bash
      run: |
        mkdir -p docs/covernator
        echo "▶ Running Covernator on ${{ inputs.project_directory }}"
        python -m geh_common.covernator_streamlit.server \
          -g \
          -o docs/covernator \
          -k stats \
          -p ${{ inputs.project_directory }}

        echo "▶ Generated files in docs/covernator:"
        ls -lah docs/covernator

        # ✅ Compact JSON for parsing
        safe_json=$(jq -c . docs/covernator/stats.json)
        echo "Compact JSON for output:"
        echo "$safe_json"

        # Extract core values
        total_cases=$(echo "$safe_json" | jq '.total_cases')
        total_scenarios=$(echo "$safe_json" | jq '.total_scenarios')
        total_groups=$(echo "$safe_json" | jq '.total_groups')

        echo "total_cases=$total_cases" >> "$GITHUB_OUTPUT"
        echo "total_scenarios=$total_scenarios" >> "$GITHUB_OUTPUT"
        echo "total_groups=$total_groups" >> "$GITHUB_OUTPUT"

        # Keep full JSON base64 for later (Step 3)
        encoded=$(echo "$safe_json" | base64 -w 0)
        echo "stats_json_b64=$encoded" >> "$GITHUB_OUTPUT"

    - name: Get CET timestamp
      id: time
      shell: bash
      run: |
        CET_TIME=$(TZ="Europe/Copenhagen" date '+%Y-%m-%d %H:%M:%S %Z')
        echo "time_cet=$CET_TIME" >> "$GITHUB_OUTPUT"

    - name: Add PR comment with summary
      uses: mshick/add-pr-comment@v2
      with:
        message-id: covernator-stats
        message: |
          🧩 **Python Covernator Commit**
          ✅ Successfully generated Covernator results for `${{ github.repository }}`

          **Stats Summary**
          • Total Cases: **${{ steps.covernator.outputs.total_cases }}**
          • Unique Scenarios: **${{ steps.covernator.outputs.total_scenarios }}**
          • Unique Groups: **${{ steps.covernator.outputs.total_groups }}**

          **geh_common version:** ${{ inputs.geh_common_version }}
          **Branch:** `${{ github.ref_name }}`
          **Generated:** ${{ steps.time.outputs.time_cet }}
