name: "Python Covernator Commit"
description: "Generate and commit Covernator coverage results, with change detection and commit guard"

inputs:
  project_directory:
    required: true
    description: "Path to the project root (where tests/ live)"
  geh_common_version:
    required: false
    default: "7.2.2"
    description: "geh_common package version"

runs:
  using: "composite"
  steps:
    # -------------------------------------------------------------------------
    # 1️⃣ Checkout domain repository
    # -------------------------------------------------------------------------
    - name: Checkout domain repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # -------------------------------------------------------------------------
    # 2️⃣ Fine-grained change detection (new)
    # -------------------------------------------------------------------------
    - name: Detect relevant file changes for Covernator
      id: covernator_changed
      uses: tj-actions/changed-files@v46
      with:
        since_last_remote_commit: true
        files: |
          source/geh_wholesale/tests/**/*.yml
          source/geh_wholesale/tests/**/test_*.py

    - name: Print change detection summary
      shell: bash
      run: |
        echo "Covernator change detection:"
        echo "Any changed: ${{ steps.covernator_changed.outputs.any_changed }}"
        echo "Changed files:"
        echo "${{ steps.covernator_changed.outputs.all_changed_files }}"

    # -------------------------------------------------------------------------
    # 3️⃣ Setup Python + UV
    # -------------------------------------------------------------------------
    - name: Setup Python
      if: steps.covernator_changed.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup uv
      if: steps.covernator_changed.outputs.any_changed == 'true'
      uses: astral-sh/setup-uv@v5

    # -------------------------------------------------------------------------
    # 4️⃣ Install geh_common
    # -------------------------------------------------------------------------
    - name: Install geh_common
      if: steps.covernator_changed.outputs.any_changed == 'true'
      shell: bash
      run: |
        echo "Installing geh_common from branch ${{ inputs.geh_common_version }}"
        uv pip install --system \
          "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@${{ inputs.geh_common_version }}#subdirectory=source/geh_common"

    # -------------------------------------------------------------------------
    # 5️⃣ Run Covernator analysis and markdown generation
    # -------------------------------------------------------------------------
    - name: Run Covernator + Markdown generator
      if: steps.covernator_changed.outputs.any_changed == 'true'
      shell: bash
      run: |
        python - <<'PYCODE'
        import os
        from geh_common.testing.covernator.entrypoints import run_and_generate_markdown

        project_dir = os.getenv("PROJECT_DIRECTORY")
        if not project_dir:
          raise ValueError("Missing PROJECT_DIRECTORY input for Covernator action.")

        print(f"🔍 Running Covernator analysis on: {project_dir}")
        run_and_generate_markdown(project_dir)
        PYCODE
      env:
        PROJECT_DIRECTORY: ${{ inputs.project_directory }}

    # -------------------------------------------------------------------------
    # 6️⃣ Commit only if markdown truly changed (local diff version)
    # -------------------------------------------------------------------------
    - name: Commit and push markdown to docs
      if: steps.covernator_changed.outputs.any_changed == 'true'
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      run: |
        set -e
        echo "📦 Checking for local differences before commit..."
        echo "🧩 Current working directory: $(pwd)"
        echo "🧾 Files in docs/covernator/:"
        ls -la docs/covernator/ || echo "(folder missing)"

        echo "🔍 Git tracked files before diff:"
        git ls-files docs/covernator/ || echo "(no tracked files)"
        echo "🔍 Git status summary before diff:"
        git status --short || echo "(no status output)"

        # Ensure Git identity is configured
        git config user.name "github-actions"
        git config user.email "ci@github.com"

        # If file does not exist at all, commit it
        if [ ! -f docs/covernator/coverage_overview.md ]; then
          echo "🆕 coverage_overview.md does not exist locally — committing new file."
          git add -f docs/covernator/coverage_overview.md
          git commit -m "🧩 Add initial Covernator results [skip ci]"
          git push origin HEAD:${BRANCH_NAME}
          exit 0
        fi

        # Compare local diff against checked-out branch
        if ! git diff --quiet docs/covernator/coverage_overview.md; then
          echo "🧩 Local differences detected; committing results."
          git add -f docs/covernator/coverage_overview.md
          git commit -m "🧩 Update Covernator results [skip ci]"
          git push origin HEAD:${BRANCH_NAME}
        else
          echo "✅ No local differences detected; skipping commit."
          exit 0
        fi
