name: "Python Covernator Commit"
description: "Generate and commit Covernator coverage results (test version for branch validation)"

inputs:
  project_directory:
    required: false
    default: "."
    description: "Project root (kept for compatibility during testing)"
  geh_common_version:
    required: false
    default: "7.2.1"
    description: "geh_common version (kept for compatibility during testing)"

runs:
  using: "composite"
  steps:
    - name: Display environment info
      id: info
      shell: bash
      run: |
        echo "🧩 Running Python Covernator Commit (test version)"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch: ${GITHUB_REF_NAME:-unknown}"
        echo "Project directory: ${{ inputs.project_directory }}"
        CET_TIME=$(TZ="Europe/Copenhagen" date '+%Y-%m-%d %H:%M:%S %Z')
        echo "The time is $CET_TIME"
        echo "time_cet=$CET_TIME" >> "$GITHUB_OUTPUT"

    - name: Add PR comment (dummy)
      uses: mshick/add-pr-comment@v2
      with:
        message-id: covernator-commit-test
        message: |
          🧪 **Covernator Commit (test branch)**
          - I am on a **test branch** of `.github`
          - Repository: `${{ github.repository }}`
          - Branch: `${{ github.ref_name }}`
          - CET time: **${{ steps.info.outputs.time_cet }}**
