name: Generate covernator files
description: Generate covernator files for a Python project and upload them as artifacts

inputs:
  project_directory:
    required: true
    description: The directory where the pyproject.toml file is located
  project_name:
    required: true
    description: The name of the project, which will also be used for the artifact name
  geh_common_version:
    required: true
    description: The version of geh_common to use. This is used to install the geh_common package from the repository.
    default: "5.8.11"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - id: covernator-step
      name: Run covernator
      shell: bash
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@geh_common_${{ inputs.geh_common_version }}#subdirectory=source/geh_common"
        cd ${{ inputs.project_directory }}
        python -c "from geh_common.covernator_streamlit import main; main()" \
          -g -o /tmp/covernator_output_folder/${{ inputs.project_name }} -k stats || \
          { echo 'Covernator not found, please install it first'; echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0; }

    - name: Upload covernator files
      id: artifact-upload-step
      if: ${{ steps.covernator-step.outputs.skip != 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: covernator-files-${{ inputs.project_name }}
        path: /tmp/covernator_output_folder/${{ inputs.project_name }}/**

    - uses: mshick/add-pr-comment@v2
      name : Add PR-comment with artifact url
      if: ${{ steps.covernator-step.outputs.skip != 'true' }}
      with:
        message-id: ${{ inputs.project_name }}
        message: |
          # Covernator (${{ inputs.project_name }})
          
          ✅ Covernator files have been generated (for ${{ inputs.project_name }}) and uploaded as artifacts.
          You can download them [here](${{ steps.artifact-upload-step.outputs.artifact-url }}).
          
          ${{ steps.covernator-step.outputs.stats }}
