name: Python Covernator Commit
description: Generate and commit Covernator coverage results, with change detection and commit guard

inputs:
  project_directory:
    required: true
    description: Path to the project root (where tests/ live)
  geh_common_version:
    required: true
    description: geh_common package version
  dh3serviceaccount_appid:
    required: true
    description: GitHub App ID for Energinet-DataHub dh3serviceaccount

runs:
  using: composite
  steps:
    # -------------------------------------------------------------------------
    # 1️⃣ Checkout repository
    # -------------------------------------------------------------------------
    - uses: actions/create-github-app-token@v2
      name: Generate Github token
      id: generate_token
      with:
        app-id: ${{ inputs.dh3serviceaccount_appid }}
        private-key: ${{ secrets.dh3serviceaccount_privatekey }}
        owner: Energinet-DataHub

    - name: Checkout domain repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        token: ${{ steps.generate_token.outputs.token }}

    # -------------------------------------------------------------------------
    # 2️⃣ Setup Python + UV
    # -------------------------------------------------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        # Instead of hardcoding an exact version, use the runner default major version
        python-version: 3.x

    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    # -------------------------------------------------------------------------
    # 3️⃣ Install geh_common
    # -------------------------------------------------------------------------
    - name: Install geh_common
      shell: bash
      run: |
        echo "Installing geh_common from branch ${{ inputs.geh_common_version }}"
        uv pip install --system \
          "geh_common @ git+https://git@github.com/Energinet-DataHub/opengeh-python-packages@geh_common_${{ inputs.geh_common_version }}#subdirectory=source/geh_common"

    # -------------------------------------------------------------------------
    # 4️⃣ Run Covernator analysis and markdown generation
    # -------------------------------------------------------------------------
    - name: Run Covernator + Markdown generator
      shell: bash
      run: |
        python - <<'PYCODE'
        import os
        from geh_common.testing.covernator.entrypoints import run_and_generate_markdown

        project_dir = os.getenv("PROJECT_DIRECTORY")
        if not project_dir:
          raise ValueError("Missing PROJECT_DIRECTORY input for Covernator action.")

        print(f"🔍 Running Covernator analysis on: {project_dir}")
        run_and_generate_markdown(project_dir)
        PYCODE
      env:
        PROJECT_DIRECTORY: ${{ inputs.project_directory }}

    # -------------------------------------------------------------------------
    # 5️⃣ Commit only if markdown truly changed (Layer 2 logic)
    # -------------------------------------------------------------------------

    - name: Configure author
      shell: bash
      run: |
        git status
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit updated coverage_overview.md
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated Covernator results
        file_pattern: docs/covernator/coverage_overview.md
