#
# Test file for testing casing validation of GitHub workflows
#

name: Valid workflow
description: |
  This workflow is used for testing and should be VALID with respect to
  casing of inputs, outputs and secrets fields.

on:
  workflow_call:
    inputs:
      first_input:
        description: First input
        required: true
      second_input:
        description: Second input
        required: false
        default: ""
    outputs:
      first_output:
        description: First output
        value: ${{ jobs.changes.outputs.magic }}
    secrets:
      first_secret:
        required: true
        description: First secret

jobs:
  changes:
    name: Determine magic
    runs-on: ubuntu-latest
    outputs:
      magic: ${{ steps.filter.outputs.magic }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            magic:
              - '.github/workflows/magic-*.yml'
