# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License..

name: Run tests - publish report
description: Run all tests with dotnet coverage and publish test reports

inputs:
  run_integration_tests:
    description: Run integration tests
    required: true
  azure_integrationtest_spn_id:
    description: Service principal ID for Azure resources
    required: true
  azure_integrationtest_tenant_id:
    description: Tenant ID for Azure resources
    required: true
  azure_integrationtest_subscription_id:
    description: Subscription ID for Azure resources
    required: true
  aspnetcore_test_contentroot_variable_name:
    description: Name of an environment variable used for configuration of WebApplicationFactory<TEntryPoint>
    required: true
  aspnetcore_test_contentroot_variable_value:
    description: Value of an environment variable used for configuration of WebApplicationFactory<TEntryPoint>
    required: true
  tests_filter_expression:
    description: Filter expression to use with dotnet test
    required: true
  tests_dll_file_path:
    description: Relative path from artifacts folder to test assembly
    required: true

runs:
  using: composite
  steps:
    - name: Login to use Azure resources from automated tests
      if: ${{ inputs.run_integration_tests == 'true' }}
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_integrationtest_spn_id }}
        tenant-id: ${{ inputs.azure_integrationtest_tenant_id }}
        subscription-id: ${{ inputs.azure_integrationtest_subscription_id }}

    # To ensure code coverage tooling is available in bin folders, teams must use 'publish' on test assemblies
    # See https://github.com/coverlet-coverage/coverlet/issues/521#issuecomment-522429394
    - name: Run tests
      shell: pwsh
      run: |
        Write-Host 'Installing dotnet.coverage ...'

        dotnet tool install --global dotnet-coverage --version 17.5.0
        # Configure content root for WebApplicationFactory<TEntryPoint>
        if ( '${{ inputs.aspnetcore_test_contentroot_variable_name }}' -ne 'empty' )
        {
          $Env:${{ inputs.aspnetcore_test_contentroot_variable_name }} = '${{ github.workspace }}${{ inputs.aspnetcore_test_contentroot_variable_value }}'
        }
        # Handle filter expression
        if ( '${{ inputs.tests_filter_expression }}' -eq 'empty' )
        {
          dotnet-coverage collect -f xml -o TestResults\coverage.xml dotnet test `
            ${{ github.workspace }}${{ inputs.tests_dll_file_path }} `
            --logger:"console;verbosity=normal" --logger:"trx;logfilename=logs.trx" `
        }
        else
        {
          dotnet-coverage collect -f xml -o TestResults\coverage.xml dotnet test `
            ${{ github.workspace }}${{ inputs.tests_dll_file_path }} `
            --filter '${{ inputs.tests_filter_expression }}' `
            --logger:"console;verbosity=normal" --logger:"trx;logfilename=logs.trx" `
        }

        $testFailures = Select-String -Path '.\TestResults\logs.trx' -Pattern '\[FAIL\]'
        $testFailures

    - name: Publish test report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        check_name: Test results for ${{ inputs.tests_dll_file_path }}
        comment_title: Test results for ${{ inputs.tests_dll_file_path }}
        comment_mode: failures
        files: |
          **/TestResults/*.trx
