name: Discover Pyproject
description: Discover pyproject.toml files in the repository
inputs:
  path:
    description: The path to discover pyproject.toml files in
    required: true
    default: ${{ github.workspace }}
outputs:
  matrix:
    description: The matrix of discovered pyproject.toml files in JSON format with name, version, and path
    value: ${{ steps.package_matrix.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Create Package Matrix
      id: package_matrix
      shell: python
      run: |
        import json
        import os
        import tomllib
        from pathlib import Path

        packages = Path("${{ inputs.path }}").rglob("pyproject.toml")
        matrix = []
        for toml in packages:
            with open(toml, "rb") as fh:
                data = tomllib.load(fh)
            name = data.get("project", {}).get("name")
            version = data.get("project", {}).get("version")
            project_data = {
              "name": name,
              "version": version,
              "path": str(toml.parent)
            }
            matrix.append(project_data)
        print(json.dumps(matrix))
        with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
            print(f"matrix={json.dumps(matrix)}", file=fh)
