name: Pack project as NuGet package
description: Pack a .NET project as either a pre-release (alpha) or release NuGet package

inputs:
  project_path:
    required: true
  build_configuration:
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: Determine version suffix property value
      id: get_version_suffix
      shell: bash
      env:
        BRANCH: ${GITHUB_REF#refs/heads/}
      run: |
        echo ${{ env.BRANCH }}
        if [[ ${{ env.BRANCH }} == 'master' || ${{ env.BRANCH }} == 'main' ]]
        then
          echo "Empty VersionSuffix"
          echo "property=''" >>$GITHUB_OUTPUT
        else
          echo "Set VersionSuffix"
          echo "property=-p:VersionSuffix=-alpha-${{ github.run_number }}" >>$GITHUB_OUTPUT
        fi

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore ${{ inputs.project_path }}

    - name: Build project
      shell: pwsh
      run: |
        dotnet build ${{ inputs.project_path }} `
          --configuration ${{ inputs.build_configuration }} `
          --no-restore `
          -p:SymbolPackageFormat=snupkg `
          -p:RepositoryCommit=${{ github.sha }} `
          ${{ steps.get_version_suffix.outputs.version_suffix_property }}

    - name: Compute directory
      shell: bash
      id: compute-dir
      run: |
        echo "project_dir=$(dirname '${{ inputs.project_path }}')" >> $GITHUB_OUTPUT
        # Get name from project_path (last part without .csproj)
        project_name=$(basename "${{ inputs.project_path }}" .csproj)
        echo "project_name=$project_name" >> $GITHUB_OUTPUT

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.20.8
      with:
        path: ${{ steps.compute-dir.outputs.project_dir }}/bin/${{ inputs.build_configuration }}
        artifact-name: sbom-${{ steps.compute-dir.outputs.project_name }}.spdx.json
        format: spdx-json
        output-file: ${{ github.workspace }}/sbom.json

    - name: Pack project
      shell: pwsh
      run: |
        dotnet pack ${{ inputs.project_path }} `
          --configuration ${{ inputs.build_configuration }} `
          --no-build `
          --include-symbols `
          -p:SymbolPackageFormat=snupkg `
          -p:RepositoryCommit=${{ github.sha }} `
          ${{ steps.get_version_suffix.outputs.property }}

    - name: Attest SBOM
      uses: actions/attest-sbom@v3
      with:
        subject-path: ${{ steps.compute-dir.outputs.project_dir }}/bin/${{ inputs.build_configuration }}/*.nupkg
        sbom-path: ${{ github.workspace }}/sbom.json
