# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Pack project as NuGet package
description: Pack a .NET project as either a pre-release (alpha) or release NuGet package

inputs:
  project_path:
    required: true
  build_configuration:
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: Get version suffix property value
      uses: Energinet-DataHub/.github/.github/actions/nuget-get-version-suffix@v15
      id: get_version_suffix

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore ${{ inputs.project_path }}

    - name: Build project
      shell: pwsh
      run: |
        dotnet build ${{ inputs.project_path }} `
          --configuration ${{ inputs.build_configuration }} `
          --no-restore `
          -p:SymbolPackageFormat=snupkg `
          -p:RepositoryCommit=${{ github.sha }} `
          ${{ steps.get_version_suffix.outputs.version_suffix_property }}

    - name: Compute directory
      shell: bash
      id: compute-dir
      run: |
        echo "project_dir=$(dirname '${{ inputs.project_path }}')" >> $GITHUB_OUTPUT
        # Get name from project_path (last part without .csproj)
        project_name=$(basename "${{ inputs.project_path }}" .csproj)
        echo "project_name=$project_name" >> $GITHUB_OUTPUT

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        path: ${{ steps.compute-dir.outputs.project_dir }}/bin/${{ inputs.build_configuration }}
        artifact-name: sbom-${{ steps.compute-dir.outputs.project_name }}.spdx.json
        format: spdx-json
        output-file: ${{ github.workspace }}/sbom.json

    - name: Pack project
      shell: pwsh
      run: |
        dotnet pack ${{ inputs.project_path }} `
          --configuration ${{ inputs.build_configuration }} `
          --no-build `
          --include-symbols `
          -p:SymbolPackageFormat=snupkg `
          -p:RepositoryCommit=${{ github.sha }} `
          ${{ steps.get_version_suffix.outputs.version_suffix_property }}

    - name: Attest SBOM
      uses: actions/attest-sbom@v3
      with:
        subject-path: ${{ steps.compute-dir.outputs.project_dir }}/bin/${{ inputs.build_configuration }}/*.nupkg
        sbom-path: ${{ github.workspace }}/sbom.json
