name: Create release tag
description: Create new release tag in repository

inputs:
  module_name:
    description: Module name
    required: true
  major_version:
    description: Major version
    required: true
  minor_version:
    description: Minor version
    required: true
  patch_version:
    description: Patch version
    required: true
  repository_path:
    description: Path to repository, i.e. Energinet-DataHub/geh-terraform-modules
    required: true
  target_branch:
    description: "Branch on which tags will be created. Default: main"
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Create release tag
      shell: pwsh
      run: |
        . ${{ github.action_path }}/Create-ReleaseTag.ps1

        Create-ReleaseTag -ModuleName "${{ inputs.module_name }}" `
        -MajorVersion ${{ inputs.major_version }} `
        -MinorVersion ${{ inputs.minor_version }} `
        -PatchVersion ${{ inputs.patch_version }} `
        -GithubRepository "${{ inputs.repository_path }}" `
        -GithubBranch "${{ inputs.target_branch }}" `
        -GithubEvent "${{ github.event_name }}" `
