name: Get release version strings
description: Return release version strings given a release name prefix

inputs:
  release_name_prefix:
    description: The release prefix, i.e. 'dotnet'
    required: true
  debug_enabled:
    description: Enable debug output
    required: false
    default: "false"

outputs:
  pr_number:
    description: The pull request number for the release i.e. '4711'
    value: ${{ steps.set_release_version_strings.outputs.pr_number }}
  release_version:
    description: Release version, i.e. 'dotnet_4711'
    value: ${{ steps.set_release_version_strings.outputs.release_version }}
  release_zip_filename:
    description: Release version ZIP filename, i.e. 'dotnet_4711.zip'
    value: ${{ steps.set_release_version_strings.outputs.release_zip_filename }}

runs:
  using: composite
  steps:
    - name: Find associated pull request
      uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v15
      id: find_pull_request
      with:
        debug_enabled: ${{ inputs.debug_enabled }}

    - name: Set release version strings
      id: set_release_version_strings
      shell: pwsh
      run: |
        $releasePrefix = "${{ inputs.release_name_prefix }}"
        $prNumber = "${{ steps.find_pull_request.outputs.pull_request_number }}"
        $releaseVersion = "$($releasePrefix)_$($prNumber)"
        $releaseZipFilename = "$($releasePrefix)_$($prNumber).zip"
        Write-Host "release_version=$releaseVersion"
        Write-Host "release_zip_filename=$releaseZipFilename"
        echo "pr_number=$prNumber" >> $env:GITHUB_OUTPUT
        echo "release_version=$releaseVersion" >> $env:GITHUB_OUTPUT
        echo "release_zip_filename=$releaseZipFilename" >> $env:GITHUB_OUTPUT
