name: Python Lint and Format
description: Lint and format a package with Ruff
inputs:
  name:
    description: The name of the package
    required: true
  path:
    description: The path to the package
    required: true
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        ignore-nothing-to-cache: true
        cache-suffix: ${{ inputs.name }}
        cache-dependency-glob: |
          ${{ inputs.path }}/pyproject.toml
          ${{ inputs.path }}/uv.lock

    - name: Lint
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff check

    - name: Format
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff format --check
