name: UV Test
description: Test a package with UV
inputs:
  name:
    description: The name of the package
    required: true
  path:
    description: The path to the package
    required: true
  tests_path:
    description: The path to the tests
    required: false
    default: tests
  pytest_addopts:
    description: Additional arguments to pass to pytest
    required: false
    default: ""
  github_token:
    description: The GitHub token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        ignore-nothing-to-cache: true
        cache-suffix: ${{ inputs.name }}
        cache-dependency-glob: |
          ${{ inputs.path }}/pyproject.toml
          ${{ inputs.path }}/uv.lock

    - name: Lint
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff check

    - name: Format
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff format --check

    - name: Test
      shell: bash
      run: uv run --directory ${{ inputs.path }} pytest ${{ inputs.tests_path }} ${{ inputs.pytest_addopts }}

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        check_name: Python test results for '${{ inputs.path }}'
        comment_title: Python test results for '${{ inputs.name }}'
        comment_mode: failures
        files: |
          ${{ inputs.path }}/coverage.xml
