name: UV Test
description: Test a package with UV
inputs:
  name:
    description: The name of the package
    required: true
  path:
    description: The path to the package
    required: true
  tests_path:
    description: The path to the tests
    required: false
    default: tests
  github_token:
    description: The GitHub token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        ignore-nothing-to-cache: true
        cache-suffix: ${{ inputs.name }}
        cache-dependency-glob: |
          ${{ inputs.path }}/pyproject.toml
          ${{ inputs.path }}/uv.lock

    - name: Lint
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff check

    - name: Format
      shell: bash
      run: uv run --directory ${{ inputs.path }} ruff format --check

    - name: Test
      shell: bash
      run: uv run --directory ${{ inputs.path }} pytest ${{ inputs.tests_path }}

    - name: Coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        github-token: ${{ inputs.github_token }}
        unique-id-for-comment: ${{ inputs.name }}-${{ inputs.path }}
        title: Coverage report for '${{ inputs.name }}'
        pytest-xml-coverage-path: ${{ inputs.path }}/coverage.xml
