name: Semver - Add
description: Add specific major/minor/patch values to a semver version.

inputs:
  version:
    description: A valid semver version
    required: true
  major:
    description: The amount to increment major version with
    required: false
    default: "0"
  minor:
    description: The amount to increment minor version with
    required: false
    default: "0"
  patch:
    description: The amount to increment patch version with
    required: false
    default: "0"

outputs:
  result:
    description: The updated version
    value: ${{ steps.update-version.outputs.result }}

runs:
  using: composite
  steps:
    - name: Update version
      id: update-version
      shell: bash
      run: |
        VERSIONS=( ${${{ inputs.version }}//./ }

        if [ ${#VERSIONS[@]} -ne 3 ]
        then
          echo "Version given does not match: major.minor.patch"
          echo "Given version: ${{ inputs.version }}"
          exit 1
        fi

        VERSIONS[0]=((VERSIONS[0]+${{ inputs.major }}))
        VERSIONS[1]=((VERSIONS[1]+${{ inputs.minor }}))
        VERSIONS[2]=((VERSIONS[2]+${{ inputs.patch }}))

        echo "::set-output name=result::${VERSIONS[0]}.${VERSIONS[1]}.${VERSIONS[2]}"
