name: Semver - Add
description: Add specific major/minor/patch values to a semver version.

inputs:
  version:
    description: A valid semver version
    required: true
  major:
    description: The amount to increment major version with
    required: false
    default: "0"
  minor:
    description: The amount to increment minor version with
    required: false
    default: "0"
  patch:
    description: The amount to increment patch version with
    required: false
    default: "0"

outputs:
  result:
    description: The updated version
    value: ${{ steps.update-version.outputs.result }}

runs:
  using: composite
  steps:
    - name: Update version
      id: update-version
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        MAJOR=${{ inputs.major }}
        MINOR=${{ inputs.minor }}
        PATCH=${{ inputs.patch }}

        COUNT=$(echo "$VERSION" | tr -cd "." | wc -c)

        if [ $COUNT -lt 2 ]
        then
            echo "Version given does not match: major.minor.patch"
            echo "Given version: $VERSION"
            exit 1
        fi

        V_0=$(echo "$VERSION" | cut -d. -f1)
        V_1=$(echo "$VERSION" | cut -d. -f2)
        V_2=$(echo "$VERSION" | cut -d. -f3)

        V_0=$((V_0+MAJOR))
        V_1=$((V_1+MINOR))
        V_2=$((V_2+PATCH))

        echo "::set-output name=result::${V_0}.${V_1}.${V_2}"
