name: Create Github token
description: Create Github app installation token to authenticate requests

inputs:
  app_id:
    description: Github app ID
    required: true
  private_key:
    description: Github app private key
    required: true

outputs:
  token:
    description: Github installation token - expires after 1 hour
    value: ${{ steps.generate_token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: Energinet-Datahub
