name: Start Azure Cosmos DB Emulator
description: Start Azure Cosmos DB Emulator on Windows runners

runs:
  using: "composite"
  steps:

    - name: Check OS
      if: runner.os != 'Windows'
      shell: pwsh
      run: |
        throw "This action only supports Windows runners."

    - name: Start Azure Cosmos DB Emulator (with retry)
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_on: error
        shell: pwsh
        command: |
          Write-Host "Start Cosmos DB Emulator..."
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          $error.Clear()
          Start-CosmosDbEmulator -NoUI -Timeout 240
          if ($error)
          {
            Write-Host "Failed"
            Exit 1
          }
