name: Build container

on:
  workflow_call:
    inputs:
      dockerfile:
        description: The path of the Dockerfile to build
        required: true
      image-name:
        description: "The full image name ex: ghcr.io/<my_container>"
        required: true
      image-tag:
        description: "The image tag"
        required: true
      docker-context:
        description: The path for the docker build context, defaults to '.'
        required: false
        default: .

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        name: Download available artifacts # this supports frontends use of artifacts
        with:
          path: artifacts/

      - name: Resolve container image name
        id: image-name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}

      - name: Build and push container image
        uses: Energinet-DataHub/.github/.github/actions/build-and-push-container@main
        with:
          dockerfile: ${{ inputs.dockerfile }}
          image_name: ${{ steps.image-name.outputs.lowercase }}
          image_tag: ${{ inputs.image-tag }}
          docker_context: ${{ inputs.docker-context && inputs.docker-context || '.'}}
