# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build containers, update and release chart

on:
  workflow_call:
    inputs:
      containers:
        description: |
          JSON string containing the containers to be built.
          Example:
          ```json
          [
            {
              deployment_name: "app",
              dockerfile: "app/Dockerfile",
              image_name: 'eo-frontend-app',
              image_tag: 'v1.2.3',
              context: '.'
            },
            {
              deployment_name: "api",
              dockerfile: "api/Dockerfile",
              image_name: 'eo-auth-api',
              image_tag: 'v1.3.1'
            }
          ]
          ```
        type: string
        required: true
      chart_folder:
        description: The path to the folder in the head (feature) branch containing the Helm charts for the services specified in `containers`.
        type: string
        required: true
      chart_version:
        description: "Optional: Override the Helm chart version to a specific version"
        type: string
        required: false
      helm_repository:
        description: "Optional: The repository to publish the chart."
        type: string
        required: false
        default: ${{ github.repository_owner }}/helm-charts
      skip_chart:
        description: "Optional: Variable for deciding if the creation of a chart should be skipped"
        type: boolean
        required: false
        default: false
      include_image_name:
        description: "Optional: Variable for deciding if the name of the image should be prepended to the name of a chart"
        type: boolean
        required: false
        default: false
      version_yaml_path_prefix:
        description: "Prefix for version tag in values file."
        type: string
        required: false
        default: "eo-base-helm-chart.deployments."

    secrets:
      deploy_key:
        description: |
          The token used to create the release and
          release the chart with a workflow dispatch to 'inputs.helm_repository'.
        required: true

    outputs:
      chart_name:
        description:
        value: ${{ jobs.chart-info.outputs.chart_name }}
      chart_version:
        description:
        value: ${{ jobs.chart-info.outputs.chart_version }}
jobs:
  build-containers-and-update-chart:
    name: Build containers
    runs-on: ubuntu-latest
    if: ${{ inputs.containers != '[]' }}
    strategy:
      matrix:
        containers: ${{fromJson(inputs.containers)}}
    steps:
      - uses: actions/checkout@v3

      - name: Build and push container image
        id: docker_build
        uses: Energinet-DataHub/.github/.github/actions/build-and-push-container@main
        with:
          dockerfile: ${{ matrix.containers.Dockerfile }}
          image-name: ${{ matrix.containers.image_name }}
          image-tag: ${{ matrix.containers.image_tag }}
          docker-context: ${{ matrix.containers.context && matrix.containers.context || '.'}}

  chart-info:
    name: Retrieve Chart Information
    outputs:
      chart_name: ${{ steps.chart-info.outputs.chart-name }}
      chart_version: ${{ inputs.chart_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get info from Chart.yaml
        id: chart-info
        uses: Energinet-DataHub/.github/.github/actions/chart-info@main
        with:
          chart-folder: ${{ inputs.chart_folder }}
          chart-version: ${{ inputs.chart_version }}
          include-image-name: ${{ inputs.include_image_name }}

  release-chart:
    name: Release domain chart
    needs: build-containers-and-update-chart
    runs-on: ubuntu-latest
    if: |
      always() &&
      inputs.skip_chart == false &&
      (needs.build-containers-and-update-chart.result == 'success' || (needs.build-containers-and-update-chart.result == 'skipped' && inputs.containers == '[]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release helm chart
        uses: Energinet-DataHub/.github/.github/actions/helm-release-bundle-chart@main
        with:
          containers: ${{ inputs.containers }}
          deploy-key: ${{ secrets.deploy_key }}
          chart-folder: ${{ inputs.chart_folder }}
          chart-repository: ${{ inputs.helm_repository }}
          chart-version: ${{ inputs.chart_version }}
          include-image-name: ${{ inputs.include_image_name }}
