
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@kerbou/add-yamllint-to-cibase

  createrelease:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:

    - name: Create release
      uses: Energinet-DataHub/.github/.github/actions/create-release-tag@v10
      with:
        MAJOR_VERSION: 10
        MINOR_VERSION: 4
        PATCH_VERSION: 0
        REPOSITORY_PATH: 'Energinet-DataHub/.github'
      env: 
        GH_TOKEN: ${{ github.token }}
