
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  yamllint_workflows:
    name: YAML linting for workflow files
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: 'Yamllint on workflow files'
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_strict: true
  #yamllint_actions:


  createrelease:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:

    - name: Create release
      uses: Energinet-DataHub/.github/.github/actions/create-release-tag@v10
      with:
        MAJOR_VERSION: 10
        MINOR_VERSION: 3
        PATCH_VERSION: 0
        REPOSITORY_PATH: 'Energinet-DataHub/.github'
      env: 
        GH_TOKEN: ${{ github.token }}