
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  #
  # License and Markdown Check
  #   
  ci_base:
    uses: ./.github/workflows/ci-base.yml
    with:
      skip_yaml_lint: false

    name: Create release tag
    runs-on: ubuntu-latest
    steps:

    - name: Create release
      uses: ./.github/actions/create-release-tag
      with:
        MAJOR_VERSION: 10
        MINOR_VERSION: 4
        PATCH_VERSION: 0
        REPOSITORY_PATH: 'Energinet-DataHub/.github'
      env: 
        GH_TOKEN: ${{ github.token }}
