# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Publish release and dispatch notification

on:
  workflow_call:
    inputs:
      CALLER_REPOSITORY_NAME:
        required: true
        description: 'Name of the local repository'
        type: string
      DEPLOY_APPLICATION:
        description: 'Deploy application'
        type: boolean
        required: false
      APPLICATION_RELEASE_NAME:
        description: 'Application release (Defaults to LATEST)'
        type: string
        required: false
      DEPLOY_INFRASTRUCTURE:
        description: 'Deploy infrastructure'
        type: boolean
        required: false
      INFRASTRUCTURE_RELEASE_NAME:
        description: 'Infrastructure release (Defaults to LATEST)'
        type: string
        required: false
    secrets:
      PAT_TOKEN:
        required: true
        description: 'Personal access token'
      ENVIRONMENT_REPOSITORY_PATH:
        required: true
        description: 'Path to the environment repository, syntax: {owner}/{repo}'

jobs:
  publish_release_and_dispatch_notification:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO_FOLDER_PATH: '${{ github.workspace }}/remote_repo'
      EVENT_TYPE: '${{ inputs.CALLER_REPOSITORY_NAME }}-deployment-request'
    steps:
      - name: Find associated pull request
        uses: jwalton/gh-find-current-pr@v1
        id: find_pull_request
        with:
          state: all
    
      - name: Fail if PR not found
        if: steps.find_pull_request.outputs.pr == ''
        run: exit 1

      - name: Set RELEASE_VERSION
        shell: bash
        run: |
          echo "RELEASE_VERSION=${{ steps.find_pull_request.outputs.pr }}" >> $GITHUB_ENV

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: '${{ secrets.ENVIRONMENT_REPOSITORY_PATH }}'
          event-type: ${{ env.EVENT_TYPE }}
          client-payload: '{"application_release_name": "${{ inputs.APPLICATION_RELEASE_NAME }}", "deploy_application": "${{ inputs.DEPLOY_APPLICATION }}", "infrastructure_release_name": "${{ inputs.INFRASTRUCTURE_RELEASE_NAME }}", "deploy_infrastructure": "${{ inputs.DEPLOY_INFRASTRUCTURE }}""}'