# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: .NET build - prerelease

# DESCRIPTION:
# This workflow will require two actions in the calling repository:
#  - dotnet-prepare-outputs
#  - dotnet-tests-prepare-outputs
#
# The workflow will build the dotnet code and add the GitHub PR and SHA
# information as .NET assembly meta data. If it is running as part
# of a PR it will also create a prerelease package containing the
# output. The prerelease name will be in the format 'dotnet_<PR-number>'.
#
# The workflow will also coordinate the creation of an artifact
# 'dotnet-tests' containing outputs necessary for executing tests.

on:
  workflow_call:
    inputs:
      solution_file_path:
        required: true
        type: string
      dotnet_version:
        description: Install specified .NET Core SDK version
        required: false
        type: string
      operating_system:
        required: false
        default: ubuntu-22.04
        type: string
      release_name_prefix:
        required: false
        type: string
        description: Use this variable if you want to prefix the release name
        default: dotnet
      project_name:
        required: false
        default: ""
        type: string
      prepare_dotnet_tests:
        required: false
        default: true
        type: boolean
jobs:
  create_prerelease:
    runs-on: ${{ inputs.operating_system }}
    name: Build ${{ inputs.solution_file_path}}
    env:
      BUILD_CONFIGURATION: Release
      TESTS_OUTPUT_PATH: ${{ github.workspace }}/tests-output
      TESTS_ZIP_FILENAME: dotnet-tests-outputs.zip
      RELEASE_FOLDER_PATH: ${{ github.workspace }}/output
      RELEASE_VERSION: ${{ inputs.release_name_prefix }}_${{ github.event.pull_request.number }}
      RELEASE_ZIP_FILENAME: ${{ inputs.release_name_prefix }}_${{ github.event.pull_request.number }}.zip

    steps:
      - name: Print Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ inputs.dotnet_version }}
        if: ${{ inputs.dotnet_version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        id: cache-nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} # hash of project files
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: dotnet restore ${{ inputs.solution_file_path }}

      - name: Build solution
        run: |
          # We build the GitHub PR and SHA (last merge commit on PR) into the .NET assembly meta data:
          #   The full 'InformationalVersion' format is '<version>+PR_<pr number>+SHA_<sha>'.
          #
          #   The value of 'SourceRevisionId' is appended to the assembly attribute 'InformationalVersion', separated by a '+' sign.
          #   See: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generateassemblyinfo
          #
          dotnet --info
          dotnet build ${{ inputs.solution_file_path }} --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} -p:SourceRevisionId=PR_${{ github.event.number }}+SHA_${{ github.sha }}

      # Call action in source (caller) repository
      - name: Prepare dotnet tests outputs
        if: ${{ inputs.prepare_dotnet_tests == true }}
        uses: ./.github/actions/dotnet-tests-prepare-outputs
        with:
          output_path: ${{ env.TESTS_OUTPUT_PATH }}

      - name: Zip dotnet tests outputs
        if: ${{ inputs.prepare_dotnet_tests == true }}
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: ${{ env.TESTS_ZIP_FILENAME }}
          directory: ${{ env.TESTS_OUTPUT_PATH }}

      - name: Upload dotnet-tests artifact
        if: ${{ inputs.prepare_dotnet_tests == true }}
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-tests
          path: ${{ env.TESTS_OUTPUT_PATH }}/${{ env.TESTS_ZIP_FILENAME }}
          if-no-files-found: error

      # Call action in source (caller) repository
      - name: Prepare dotnet outputs
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        uses: ./.github/actions/dotnet-prepare-outputs
        with:
          output_path: ${{ env.RELEASE_FOLDER_PATH }}
          project_name: ${{ inputs.project_name }}

      - name: Zip files for prerelease
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: ${{ env.RELEASE_ZIP_FILENAME }}
          directory: ${{ env.RELEASE_FOLDER_PATH }}

      - name: Create pre-release
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        uses: Energinet-DataHub/.github/.github/actions/github-create-release@kerbou/refactor-create-release-for-mergequeues
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          prerelease: true
          title: ${{ env.RELEASE_VERSION }}
          files: |
            ${{ env.RELEASE_FOLDER_PATH }}/${{ env.RELEASE_ZIP_FILENAME }}
