name: Generate Sealed Secret

on:
  workflow_call:
    inputs:
      SECRET_NAME:
        description: The name of the value to encrypt
        type: string
        required: true

      NAMESPACE:
        description: Kubernetes namespace in which the secret can be used in
        type: string
        required: true

      ECHO_OUTPUT:
        description: Whether or not to echo the output
        type: boolean
        required: true
        default: false

    secrets:
      VALUE:
          description: The value to encrypt
          required: true

      PUBLIC_CERTIFICATE:
        description: The certificate used to encrypt the secret
        required: true

jobs:
  generate_secret:
    name: Pass input and secrets to sealed secret generator
    runs-on: ubuntu-latest
    outputs:
      sealed_secret: ${{ steps.generate_secret.outputs.sealed_secret }}
    steps:
      - name: Fetch kubeseal CLI
        shell: bash
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.1/kubeseal-0.17.1-linux-amd64.tar.gz;
          tar -xvf kubeseal-0.17.1-linux-amd64.tar.gz kubeseal;
          rm kubeseal-0.17.1-linux-amd64.tar.gz

      - name: Write certificate to file
        shell: bash
        run: |
          echo "${{ secrets.PUBLIC_CERTIFICATE }}" > key.crt

      - name: Generate and output secret
        id: generate_secret
        shell: bash
        run: |
          export sealed_secret=`echo "${{ secrets.VALUE }}" | ./kubeseal --cert ./key.crt --name "${{ inputs.SECRET_NAME }}" --namespace "${{ inputs.NAMESPACE }}" --raw --scope strict`
          echo "::set-output name=sealed_secret::$sealed_secret"

      - name: Echo secret
        if: inputs.ECHO_OUTPUT == true
        shell: bash
        run: >
          echo -e "
          ---Secret Generated---\n
          (Hint: Don't include single quotes)\n
          secret_name: \t'${{ inputs.SECRET_NAME }}'\n
          namespace: \t'${{ inputs.NAMESPACE }}'\n
          encrypted_secret: '${{ steps.generate_secret.outputs.sealed_secret }}'
          "
