# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Version increment check

on:
  workflow_call:
    inputs:
      yaml_file:
        description: The yaml file to find the value in.
        required: true
        type: string
      yaml_path:
        description: The yaml path in the file to compare the semver of.
        required: true
        type: string

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main to get latest tag
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get Previous tag
        id: previous_tag
        uses: Energinet-Datahub/.github/.github/actions/yaml-get@main
        with:
          yaml_file: ${{ inputs.yaml_file }}
          yaml_path: ${{ inputs.yaml_path }}

      - name: Check if previous tag is valid semver
        id: is_prev_tag_valid
        uses: rubenesp87/semver-validation-action@cd30707b188980006854de19df716fc9cf39f37f
        # Accept old versions to be invalid since new versions are checked they are valid
        continue-on-error: true
        with:
          version: ${{ steps.previous_tag.outputs.result }}

      - name: Get next valid semvers
        id: semvers
        if: steps.is_prev_tag_valid.outcome == 'success'
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.result }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get current tag
        id: current_tag
        uses: Energinet-Datahub/.github/.github/actions/yaml-get@main
        with:
          yaml_file: ${{ inputs.yaml_file }}
          yaml_path: ${{ inputs.yaml_path }}

      - name: Check if current tag is valid semver
        uses: rubenesp87/semver-validation-action@cd30707b188980006854de19df716fc9cf39f37f
        with:
          version: ${{ steps.current_tag.outputs.result }}

      - name: Check versions
        if: ${{ steps.is_prev_tag_valid.outcome == 'success' && steps.current_tag.outputs.result != steps.semvers.outputs.patch && steps.current_tag.outputs.result != steps.semvers.outputs.minor && steps.current_tag.outputs.result != steps.semvers.outputs.major }}
        run: |
          echo "The version ${{ steps.current_tag.outputs.result }} must be an increment of the current version on main ${{ steps.previous_tag.outputs.tag }}."
          exit 1
